### ISSUE TITLE
Ordering guarantees

### ISSUE THREAD

**Issue by benstadin** [max0x7ba/atomic_queue#3]
I'm just about to check out your queue. I'm currently using MoodyCamel ConcurrentQueue, but in one of my projects I now come across the limitation that there are no ordering guarantees.

Are items enqueued to atomic_queue dequeued in (almost) the same order?

**Comment by max0x7ba** [comment]
On x86-64 the operations happen to be totally ordered because:

- `try_push/try_pop` use `compare_exchange_strong(..., std::memory_order_acquire)` and it compiles into `lock cmpxchg`, which is totally ordered.
- `push/pop` use `fetch_add(1, std::memory_order_acquire)` and it compiles into `lock xadd`, which is totally ordered.

In other words, even though the code doesn't request totally ordered atomic operations, on Intel they are totally ordered because there are no atomic read-modify-write instructions on Intel with less strict memory order.

Some addition info: https://stackoverflow.com/a/56279904/412080

**Comment by benstadin** [comment]
Thank you for the quick reply. 

Is this also te case for ARM platforms? Specifically, ARM Cortex A7 based Raspberry Pi 3b, and the newer Raspberry PI 4 with Cortex A72.

**Comment by max0x7ba** [comment]
> Is this also te case for ARM platforms?

I am not familiar with ARM platforms, so cannot answer that.

**Comment by max0x7ba** [comment]
I have added a template argument to enable the totally ordered mode (it is off by default). In this mode consumers receive messages in the same FIFO order the messages were posted. This mode is supported for `push` and `pop` functions only, but for not the `try_` versions (because these cannot guarantee FIFO queueing). On Intel x86 the totally ordered mode comes at 0 cost.

**Comment by benstadin** [comment]
That's great stuff. Thank you!
