### ISSUE TITLE
Ever incresing queue size

### ISSUE THREAD

**Issue by ZEPORATH** [max0x7ba/atomic_queue#44]
Hi, I am trying to use the queue in my project, where opencv frames are queued. I needed to store a queue size of 5(for most recent frames), but what I observe is that if the consumer thread is not activated, and the producer will keep pushing the data in queue which leads to  the size of queue ever increasing. At the rate of 30fps, my queue size is crossing 1gb in just few min, instead of few mb(s) for just 5 frames. 

Code snippets are as below:
1. Declaration:
 `    atomic_queue::AtomicQueueB2<FramePacket> m_LiveFrameBuff{5}; `
2. Producer call:
  ```  
      auto temp = framePacket;
      m_LiveFrameBuff.push(temp);
```
3. Consumer call:
 ```
   void FrameBuffManager::getLiveFrame(FramePacket &ret)
{
    funcname();
    if (m_stopworkers.load())
        return;
    ret = m_LiveFrameBuff.pop();
    return;
}
```
4. Size print check
```
std::cout << m_LiveFrameBuff.was_size() << std::endl;
```

The readme also mentions about other available queues like `OptimistAtomicQueue2`, but I am unable to find/use it. Can more simpler use case examples be provided for the respective available containers. It will be really helpful.

**Comment by ZEPORATH** [comment]
Actually I get it, the capacity is 4096 elements, so now once this is full, the code will busy wait until a consumer starts emptying it. I was looking for some kind of FIFO buffer where a fixed size can be maintained, and if the this HWM is hit, can I change the capacity to a lower value, if yes how?

**Comment by max0x7ba** [comment]
> I was looking for some kind of FIFO buffer where a fixed size can be maintained and if the this HWM is hit the old data is thrown and new data is pushed in, like if the buffer can have some sort of discard policy. 

_Queues'_ only job is to _store_ the elements, not _discard_ them. 

_Rolling windows_, on the other hand, are designed to keep the last N elements and discard the oldest, according to your policy.

You should note that `push` is designed for the use case that the queue is never full. And `pop` for the use case that the queue is never empty. Otherwise, you should use `try_` calls. It is safe to mix `try_push` with `pop` and `push` with `try_pop`. As well as `push` with `try_push` and `pop` with `try_pop`, but this would be less trivial code, which makes it harder to reason about and ensure it works as expected.

You can implement rolling window functionality in multiple ways. Solutions depend on whether the number of producers is more than 1, and whether the number of consumers is more than 1.

For 1-producer-1-consumer use case:

1. The producer invokes `try_push`. If that succeeds, you're done.
2. Otherwise, the producer does `try_pop` to extract the oldest element. Ignore the return value of the call and goto 1.

Note, that there is an inherent race condition between steps 1 and 2: `try_push` fails in the producer; `pop`/`try_pop` in the consumer succeeds and the queue is not full any more; meanwhile producer does `try_pop` while it is no longer necessary to discard the last element.

`try_push` returns `false`, meanwhile a consumer extracts the last

> Anyway, Can I change the capacity to a lower value, if yes how?

These queues are designed for lowest possible latency. That's why the queue capacity is immutable.

---

Alternatively, for your problem of one prolific producer and one slow consumer that is only interested in the last N elements, I would start with a simple `std::list<T>` along with `std::mutex` and `std::condition_variable`. Both producer and consumer lock the mutex before modifying the list. This way the producer can make sure that the list never grows beyond N elements on `push`. The condition variable only needs to be signalled when `push` changes the rolling window state from empty to non-empty. And then benchmark to see whether you do need anything beyond that, like this lockless queue. 

These lockless queues are designed for the use case when blocking queues become the bottleneck in your application. Your use case of 30 push/sec is rather pedestrian, you shouldn't need anything beyond basic `std::` components for that.
