### ISSUE TITLE
how to put struct to queue

### ISSUE THREAD

**Issue by chansonZ** [max0x7ba/atomic_queue#48]
Can anyone help?
```
typedef struct {
    int a;
    char b[32];
} UserData;
```

compile error when:
```
constexpr unsigned CAPACITY = 1024;
AtomicQueue<UserData, CAPACITY> q; 
```

**Comment by max0x7ba** [comment]
When you report problems, you should [provide complete reproducible example with the error message](https://stackoverflow.com/help/minimal-reproducible-example), so that no guesswork or undue effort is required to help you. 

---

Your code doesn't compile because you use a queue type for atomic elements, whereas `UserData` isn't the one. You should always read documentation before using something or asking questions.

A fix:

```
atomic_queue::AtomicQueue2<UserData, CAPACITY> q;
```
